#macro MASTER_IP "127.0.0.1"
#macro MASTER_PORT 7777

enum PACKET {
	GAMESERVER_REGISTER,
	GAMESERVER_NEWPLAYER,
	GAMESERVER_CLOSE,
	
	CLIENT_REGISTER,
	CLIENT_DISCONNECT,
	CLIENT_CONNECTFAIL,
	
	CONNECTED,
	MASTERSERVER_CLOSE
}

// 클라이언트 전용
global.server_ip = -1;
global.server_port = -1;