draw_set_font(font_main);

enum PACKET {
	GAMESERVER_REG,
	GAMESERVER_CONNECTED,
	GAMESERVER_NEWPLAYER,
	GAMESERVER_PASSID,
	GAMESERVER_CLOSE,
	
	MASTERSERVER_CLOSE,
	
	CLIENT_REG,
	CLIENT_CONNECTED,
	CLIENT_GETID,
	CLIENT_DISCONNECT,
	CLIENT_CONNECTFAIL
}
